/** Field labels and sheet titles aligned with web (Frontend form labels). */
export const FORM_LABELS = {
  customer: {
    addTitle: 'Add Customer',
    editTitle: 'Edit Customer',
    name: 'Name',
    company: 'Company (optional)',
    email: 'Email (optional)',
    phone: 'Phone (optional)',
    save: 'Save',
    add: 'Add customer',
  },
  product: {
    addTitle: 'Add Product',
    editTitle: 'Edit Product',
    image: 'Product image (optional)',
    name: 'Product Name *',
    sku: 'SKU (optional)',
    barcode: 'Barcode (optional)',
    sellingPrice: 'Selling Price *',
    costPrice: 'Cost Price (optional)',
    quantityOnHand: 'Quantity on Hand',
    create: 'Create Product',
    save: 'Save changes',
    delete: 'Delete',
  },
  expense: {
    addTitle: 'Add Expense',
    category: 'Category',
    amount: 'Amount',
    description: 'Description (optional)',
    expenseDate: 'Expense Date',
    paymentMethod: 'Payment Method (Optional)',
    notes: 'Notes (Optional)',
    record: 'Record Expense',
  },
  material: {
    addTitle: 'New Material',
    restockTitle: 'Restock Item',
    itemName: 'Item Name *',
    sku: 'SKU (optional)',
    category: 'Category (optional)',
    unit: 'Unit',
    quantityOnHand: 'Quantity on Hand',
    reorderLevel: 'Reorder Level',
    unitCost: 'Unit Cost (optional)',
    quantityToAdd: 'Quantity to add',
    reference: 'Reference (optional)',
    add: 'Add Material',
    restock: 'Restock',
  },
  lead: {
    addTitle: 'New Lead',
    leadName: 'Lead Name',
    company: 'Company (optional)',
    email: 'Email (optional)',
    phone: 'Phone (optional)',
    source: 'Lead Source (optional)',
    otherSource: 'Other source (optional)',
    save: 'Create Lead',
  },
  task: {
    addTitle: 'Create task',
    title: 'Title',
    description: 'Description (optional)',
    dueDate: 'Due date',
    create: 'Create task',
  },
  cart: {
    selectCustomer: 'Select Customer',
    payment: 'Payment',
    phone: 'Phone',
    nameOptional: 'Name (optional)',
    findOrAdd: 'Find or add customer',
    walkIn: 'Walk-in Customer',
    paymentMethod: 'Payment method',
    amountTendered: 'Amount tendered',
    mobileMoneyNumber: 'Mobile money number',
    completeSale: 'Complete Payment',
  },
} as const;
